project:
  title: ld43
  authors: ['Andrei Rudenko']
  description : 'Ludum Dare 43 entry'
  version: '1.0.0'
  sources: ['src']
  assets: ['assets']
  defines: [no_debug_console]
  shaders: []
  libraries: []

input:
  mouse: true
  keyboard: true
  gamepad: true
  touch: true
  pen: false

android:
  package: com.clayengine.ld43
  orientation: 'portrait'

app:
  name: ld43
  icon: 'res/icon.png'
  
html5:
  webgl: true
  canvas: 'kanvas'
  script: 'game'
  width: 540 # 540
  height: 960 # 960
  server_port: 8080
  html_file: ''
  favicon: 'res/icon.png'
  minify: false

windows:
  graphics: 'direct3d11'
  
compiler:
  output: 'build'
  parameters: ['-dce full']
  options: ['']
  haxe: ''
  kha: ''
  ffmpeg: ''
